package com.recipeeditor.exporter;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.recipeeditor.RecipeEditorMod;
import com.recipeeditor.config.CustomRecipeData;
import com.recipeeditor.config.RecipeEditorConfig;
import com.recipeeditor.config.RecipeTypeEnum;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.registry.Registries;
import net.minecraft.util.Identifier;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public class DatapackExporter {
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    public static boolean exportToZip() {
        Path configDir = FabricLoader.getInstance().getConfigDir();
        File zipFile = configDir.resolve("RecipeEditorDatapack.zip").toFile();

        try (FileOutputStream fos = new FileOutputStream(zipFile);
             ZipOutputStream zos = new ZipOutputStream(fos)) {

            // 1. pack.mcmeta
            JsonObject mcmeta = new JsonObject();
            JsonObject pack = new JsonObject();
            pack.addProperty("pack_format", 61); // Minecraft 1.21.4 pack format
            pack.addProperty("description", "Generated by Recipe Editor (byMr712)");
            mcmeta.add("pack", pack);

            addZipEntry(zos, "pack.mcmeta", GSON.toJson(mcmeta));

            // 2. Recipes
            RecipeEditorConfig config = RecipeEditorConfig.getInstance();
            for (CustomRecipeData recipe : config.recipes.values()) {
                if (!recipe.enabled) continue;

                Identifier resId = Identifier.tryParse(recipe.resultItemId);
                String recipeName = (resId != null ? resId.getPath() : "custom_recipe") + "_" + recipe.type.name().toLowerCase(Locale.ROOT);
                JsonObject recipeJson = buildRecipeJson(recipe);
                if (recipeJson != null) {
                    addZipEntry(zos, "data/recipeeditor/recipe/" + recipeName + ".json", GSON.toJson(recipeJson));
                }
            }

            RecipeEditorMod.LOGGER.info("Successfully exported datapack to {}", zipFile.getAbsolutePath());
            return true;
        } catch (IOException e) {
            RecipeEditorMod.LOGGER.error("Failed to export datapack", e);
            return false;
        }
    }

    private static void addZipEntry(ZipOutputStream zos, String path, String content) throws IOException {
        ZipEntry entry = new ZipEntry(path);
        zos.putNextEntry(entry);
        zos.write(content.getBytes(StandardCharsets.UTF_8));
        zos.closeEntry();
    }

    private static JsonObject buildRecipeJson(CustomRecipeData recipe) {
        JsonObject root = new JsonObject();

        if (recipe.type == RecipeTypeEnum.SHAPED_CRAFTING) {
            root.addProperty("type", "minecraft:crafting_shaped");
            root.addProperty("category", "misc");

            JsonArray pattern = new JsonArray();
            pattern.add("ABC");
            pattern.add("DEF");
            pattern.add("GHI");
            root.add("pattern", pattern);

            JsonObject key = new JsonObject();
            char[] chars = new char[]{'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'};
            for (int i = 0; i < 9; i++) {
                String slotStr = recipe.getSlotString(i);
                if (!slotStr.equals("minecraft:air") && !slotStr.isEmpty()) {
                    JsonObject ingObj = new JsonObject();
                    if (slotStr.startsWith("#")) {
                        ingObj.addProperty("tag", slotStr.substring(1));
                    } else {
                        ingObj.addProperty("item", slotStr);
                    }
                    key.add(String.valueOf(chars[i]), ingObj);
                } else {
                    // Empty slot representation
                    JsonObject emptyObj = new JsonObject();
                    emptyObj.addProperty("item", "minecraft:air");
                    key.add(String.valueOf(chars[i]), emptyObj);
                }
            }
            root.add("key", key);

            JsonObject result = new JsonObject();
            result.addProperty("id", recipe.resultItemId);
            result.addProperty("count", recipe.resultCount);
            root.add("result", result);

            return root;
        } else if (recipe.type == RecipeTypeEnum.SHAPELESS_CRAFTING) {
            root.addProperty("type", "minecraft:crafting_shapeless");
            root.addProperty("category", "misc");

            JsonArray ingredients = new JsonArray();
            for (int i = 0; i < 9; i++) {
                String slotStr = recipe.getSlotString(i);
                if (!slotStr.equals("minecraft:air") && !slotStr.isEmpty()) {
                    JsonObject ingObj = new JsonObject();
                    if (slotStr.startsWith("#")) {
                        ingObj.addProperty("tag", slotStr.substring(1));
                    } else {
                        ingObj.addProperty("item", slotStr);
                    }
                    ingredients.add(ingObj);
                }
            }
            root.add("ingredients", ingredients);

            JsonObject result = new JsonObject();
            result.addProperty("id", recipe.resultItemId);
            result.addProperty("count", recipe.resultCount);
            root.add("result", result);

            return root;
        } else if (recipe.type == RecipeTypeEnum.SMELTING) {
            root.addProperty("type", "minecraft:smelting");
            root.addProperty("category", "misc");

            String slotStr = recipe.getSlotString(0);
            JsonObject ingObj = new JsonObject();
            if (slotStr.startsWith("#")) {
                ingObj.addProperty("tag", slotStr.substring(1));
            } else {
                ingObj.addProperty("item", slotStr.isEmpty() || slotStr.equals("minecraft:air") ? "minecraft:stone" : slotStr);
            }
            root.add("ingredient", ingObj);
            root.addProperty("result", recipe.resultItemId);
            root.addProperty("experience", recipe.experience);
            root.addProperty("cookingtime", recipe.cookingTime);

            return root;
        } else if (recipe.type == RecipeTypeEnum.STONECUTTING) {
            root.addProperty("type", "minecraft:stonecutting");

            String slotStr = recipe.getSlotString(0);
            JsonObject ingObj = new JsonObject();
            if (slotStr.startsWith("#")) {
                ingObj.addProperty("tag", slotStr.substring(1));
            } else {
                ingObj.addProperty("item", slotStr.isEmpty() || slotStr.equals("minecraft:air") ? "minecraft:stone" : slotStr);
            }
            root.add("ingredient", ingObj);

            JsonObject result = new JsonObject();
            result.addProperty("id", recipe.resultItemId);
            result.addProperty("count", recipe.resultCount);
            root.add("result", result);

            return root;
        }

        return null;
    }
}
