package com.recipeeditor.exporter;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.recipeeditor.RecipeEditorMod;
import com.recipeeditor.config.CustomRecipeData;
import com.recipeeditor.config.RecipeEditorConfig;
import com.recipeeditor.config.RecipeTypeEnum;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.util.Identifier;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.Locale;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public class DatapackExporter {
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    public static boolean exportToZip() {
        try {
            Path configDir = FabricLoader.getInstance().getConfigDir();
            File zipFile = configDir.resolve("RecipeEditorDatapack.zip").toFile();

            try (FileOutputStream fos = new FileOutputStream(zipFile);
                 ZipOutputStream zos = new ZipOutputStream(fos)) {

                // 1. pack.mcmeta
                JsonObject mcmeta = new JsonObject();
                JsonObject pack = new JsonObject();
                pack.addProperty("pack_format", 61); // Minecraft 1.21.4 pack format
                pack.addProperty("description", "Universal Recipes generated by Recipe Editor (byMr712)");
                mcmeta.add("pack", pack);

                addZipEntry(zos, "pack.mcmeta", GSON.toJson(mcmeta));

                // 2. Recipes
                RecipeEditorConfig config = RecipeEditorConfig.getInstance();
                for (CustomRecipeData recipe : config.recipes.values()) {
                    if (!recipe.enabled || recipe.resultItemId.equals("minecraft:air")) continue;

                    Identifier resId = Identifier.tryParse(recipe.resultItemId);
                    String recipeName = (resId != null ? resId.getPath() : "custom_recipe") + "_" + recipe.type.name().toLowerCase(Locale.ROOT);
                    JsonObject recipeJson = buildRecipeJson(recipe);
                    if (recipeJson != null) {
                        addZipEntry(zos, "data/recipeeditor/recipe/" + recipeName + ".json", GSON.toJson(recipeJson));
                    }
                }

                RecipeEditorMod.LOGGER.info("Successfully exported datapack to {}", zipFile.getAbsolutePath());
                return true;
            }
        } catch (Throwable t) {
            RecipeEditorMod.LOGGER.error("Failed to export datapack", t);
            return false;
        }
    }

    private static void addZipEntry(ZipOutputStream zos, String path, String content) throws IOException {
        ZipEntry entry = new ZipEntry(path);
        zos.putNextEntry(entry);
        zos.write(content.getBytes(StandardCharsets.UTF_8));
        zos.closeEntry();
    }

    private static JsonObject buildRecipeJson(CustomRecipeData recipe) {
        JsonObject root = new JsonObject();

        if (recipe.type == RecipeTypeEnum.SHAPED_CRAFTING) {
            root.addProperty("type", "minecraft:crafting_shaped");
            root.addProperty("category", "misc");

            JsonObject key = new JsonObject();
            char[] chars = new char[]{'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'};
            StringBuilder[] rows = new StringBuilder[]{new StringBuilder(), new StringBuilder(), new StringBuilder()};

            for (int r = 0; r < 3; r++) {
                for (int c = 0; c < 3; c++) {
                    int i = r * 3 + c;
                    String slotStr = recipe.getSlotString(i);
                    if (!slotStr.equals("minecraft:air") && !slotStr.isEmpty()) {
                        char ch = chars[i];
                        rows[r].append(ch);
                        JsonObject ingObj = new JsonObject();
                        if (slotStr.startsWith("#")) {
                            ingObj.addProperty("tag", slotStr.substring(1));
                        } else {
                            ingObj.addProperty("item", slotStr);
                        }
                        key.add(String.valueOf(ch), ingObj);
                    } else {
                        rows[r].append(' ');
                    }
                }
            }

            JsonArray pattern = new JsonArray();
            for (StringBuilder row : rows) {
                pattern.add(row.toString());
            }
            root.add("pattern", pattern);
            root.add("key", key);

            JsonObject result = new JsonObject();
            result.addProperty("id", recipe.resultItemId);
            result.addProperty("count", recipe.getResultCountForType(recipe.type));
            root.add("result", result);

            return root;
        } else if (recipe.type == RecipeTypeEnum.SHAPELESS_CRAFTING) {
            root.addProperty("type", "minecraft:crafting_shapeless");
            root.addProperty("category", "misc");

            JsonArray ingredients = new JsonArray();
            for (int i = 0; i < 9; i++) {
                String slotStr = recipe.getSlotString(i);
                if (!slotStr.equals("minecraft:air") && !slotStr.isEmpty()) {
                    JsonObject ingObj = new JsonObject();
                    if (slotStr.startsWith("#")) {
                        ingObj.addProperty("tag", slotStr.substring(1));
                    } else {
                        ingObj.addProperty("item", slotStr);
                    }
                    ingredients.add(ingObj);
                }
            }
            root.add("ingredients", ingredients);

            JsonObject result = new JsonObject();
            result.addProperty("id", recipe.resultItemId);
            result.addProperty("count", recipe.getResultCountForType(recipe.type));
            root.add("result", result);

            return root;
        } else if (recipe.type == RecipeTypeEnum.SMELTING || recipe.type == RecipeTypeEnum.BLASTING || recipe.type == RecipeTypeEnum.SMOKING) {
            String typeId = recipe.type == RecipeTypeEnum.BLASTING ? "minecraft:blasting" :
                    (recipe.type == RecipeTypeEnum.SMOKING ? "minecraft:smoking" : "minecraft:smelting");
            root.addProperty("type", typeId);
            root.addProperty("category", "misc");

            String slotStr = recipe.getSlotString(0);
            JsonObject ingObj = new JsonObject();
            if (slotStr.startsWith("#")) {
                ingObj.addProperty("tag", slotStr.substring(1));
            } else {
                ingObj.addProperty("item", slotStr.isEmpty() || slotStr.equals("minecraft:air") ? "minecraft:stone" : slotStr);
            }
            root.add("ingredient", ingObj);

            JsonObject result = new JsonObject();
            result.addProperty("id", recipe.resultItemId);
            root.add("result", result);

            root.addProperty("experience", recipe.experience);
            int cookingTime = recipe.cookingTime > 0 ? recipe.cookingTime : (recipe.type == RecipeTypeEnum.SMELTING ? 200 : 100);
            root.addProperty("cookingtime", cookingTime);

            return root;
        } else if (recipe.type == RecipeTypeEnum.STONECUTTING) {
            root.addProperty("type", "minecraft:stonecutting");

            String slotStr = recipe.getSlotString(0);
            JsonObject ingObj = new JsonObject();
            if (slotStr.startsWith("#")) {
                ingObj.addProperty("tag", slotStr.substring(1));
            } else {
                ingObj.addProperty("item", slotStr.isEmpty() || slotStr.equals("minecraft:air") ? "minecraft:stone" : slotStr);
            }
            root.add("ingredient", ingObj);

            JsonObject result = new JsonObject();
            result.addProperty("id", recipe.resultItemId);
            result.addProperty("count", recipe.getResultCountForType(recipe.type));
            root.add("result", result);

            return root;
        }

        return null;
    }
}
